"""SQLAlchemy Core definitions mirroring migrations 0009 to 0011 and 0013 (the migrations are the
source of truth)."""

from sqlalchemy import (
    ARRAY,
    BigInteger,
    Column,
    Date,
    DateTime,
    Integer,
    LargeBinary,
    MetaData,
    Numeric,
    Table,
    Text,
    Uuid,
)
from sqlalchemy.dialects.postgresql import JSONB

metadata = MetaData(schema="cbam")

documents = Table(
    "documents",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("tenant_id", Uuid, nullable=False),
    Column("created_at", DateTime(timezone=True)),
    Column("created_by", Uuid),
)

document_versions = Table(
    "document_versions",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("tenant_id", Uuid, nullable=False),
    Column("document_id", Uuid, nullable=False),
    Column("version", Integer, nullable=False),
    Column("storage_key", Text, nullable=False),
    Column("sha256", Text, nullable=False),
    Column("size_bytes", BigInteger, nullable=False),
    Column("mime_detected", Text, nullable=False),
    Column("original_filename", Text, nullable=False),
    Column("uploaded_by_type", Text, nullable=False),
    Column("uploaded_by_id", Uuid),
    Column("scan_state", Text, nullable=False),
    Column("uploaded_at", DateTime(timezone=True)),
)

import_batches = Table(
    "import_batches",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("tenant_id", Uuid, nullable=False),
    Column("file_sha256", Text),
    Column("document_version_id", Uuid),
    Column("filename", Text),
    Column("acquisition_method", Text, nullable=False),
    Column("cds_report_type", Text),
    Column("eori", Text),
    Column("window_start", Date),
    Column("window_end", Date),
    Column("source_owner", Text),
    Column("acquired_on", Date),
    Column("idempotency_key", Text),
    Column("request_fingerprint", LargeBinary, nullable=False),
    Column("status", Text, nullable=False),
    Column("rows_total", Integer, nullable=False),
    Column("rows_processed", Integer, nullable=False),
    Column("rows_valid", Integer, nullable=False),
    Column("rows_rejected", Integer, nullable=False),
    Column("lines_created", Integer, nullable=False),
    Column("lines_unchanged", Integer, nullable=False),
    Column("failure_reason", Text),
    Column("report_layout_version_id", Uuid),
    Column("layout_status", Text),
    Column("attempts", Integer, nullable=False),
    Column("lease_expires_at", DateTime(timezone=True)),
    Column("lease_owner", Uuid),
    Column("created_at", DateTime(timezone=True)),
    Column("created_by", Uuid),
    Column("updated_at", DateTime(timezone=True)),
    Column("row_version", Integer, nullable=False),
)

source_rows = Table(
    "source_rows",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("tenant_id", Uuid, nullable=False),
    Column("batch_id", Uuid, nullable=False),
    Column("row_number", Integer, nullable=False),
    Column("raw", JSONB, nullable=False),
    Column("row_sha256", Text, nullable=False),
    Column("created_at", DateTime(timezone=True)),
)

row_exceptions = Table(
    "row_exceptions",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("tenant_id", Uuid, nullable=False),
    Column("batch_id", Uuid, nullable=False),
    Column("source_row_id", Uuid),
    Column("row_number", Integer, nullable=False),
    Column("field", Text, nullable=False),
    Column("code", Text, nullable=False),
    Column("severity", Text, nullable=False),
    Column("message", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("resolved_by", Uuid),
    Column("resolved_at", DateTime(timezone=True)),
    Column("resolution_reason", Text),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
    Column("row_version", Integer, nullable=False),
)

parties = Table(
    "parties",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("tenant_id", Uuid, nullable=False),
    Column("eori", Text),
    Column("name", Text),
    Column("created_at", DateTime(timezone=True)),
)

declarations = Table(
    "declarations",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("tenant_id", Uuid, nullable=False),
    Column("mrn", Text, nullable=False),
    Column("version", Integer, nullable=False),
    Column("supersedes_id", Uuid),
    Column("acceptance_date", Date, nullable=False),
    Column("acceptance_at", DateTime(timezone=True)),
    Column("procedure_code", Text),
    Column("additional_procedure_codes", ARRAY(Text)),
    Column("importer_party_id", Uuid),
    Column("declarant_party_id", Uuid),
    Column("representative_party_id", Uuid),
    Column("representation_type", Text, nullable=False),
    Column("eori_context", Text),
    Column("entry_method", Text, nullable=False),
    Column("batch_id", Uuid, nullable=False),
    Column("content_sha256", Text, nullable=False),
    Column("hash_version", Integer, nullable=False),
    Column("created_at", DateTime(timezone=True)),
)

import_lines = Table(
    "import_lines",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("tenant_id", Uuid, nullable=False),
    Column("declaration_id", Uuid, nullable=False),
    Column("item_no", Integer, nullable=False),
    Column("version", Integer, nullable=False),
    Column("supersedes_id", Uuid),
    Column("commodity_code", Text, nullable=False),
    Column("description", Text),
    Column("net_mass_kg", Numeric(20, 6, asdecimal=True), nullable=False),
    Column("supplementary_qty", Numeric(20, 6, asdecimal=True)),
    Column("supplementary_unit", Text),
    Column("customs_value_source", Numeric(24, 8, asdecimal=True), nullable=False),
    Column("customs_value_currency", Text, nullable=False),
    Column("customs_value_gbp", Numeric(18, 2, asdecimal=True)),
    Column("customs_value_gbp_note", Text),
    Column("fx_method", Text),
    Column("valuation_basis", Text),
    Column("value_source", Text, nullable=False),
    Column("value_override_reason", Text),
    Column("country_of_origin_declared", Text, nullable=False),
    Column("cpc", Text),
    Column("batch_id", Uuid, nullable=False),
    Column("source_row_id", Uuid, nullable=False),
    Column("entry_method", Text, nullable=False),
    Column("change_reason", Text),
    Column("content_sha256", Text, nullable=False),
    Column("hash_version", Integer, nullable=False),
    Column("created_at", DateTime(timezone=True)),
)

import_line_sources = Table(
    "import_line_sources",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("tenant_id", Uuid, nullable=False),
    Column("import_line_id", Uuid, nullable=False),
    Column("source_row_id", Uuid, nullable=False),
    Column("report_type", Text),
    Column("role", Text, nullable=False),
    Column("created_at", DateTime(timezone=True)),
)

report_row_keys = Table(  # migration 0013: the join key of a header or tax-lines row
    "report_row_keys",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("tenant_id", Uuid, nullable=False),
    Column("batch_id", Uuid, nullable=False),
    Column("source_row_id", Uuid, nullable=False),
    Column("report_type", Text, nullable=False),
    Column("mrn", Text, nullable=False),
    Column("item_no", Integer),
    Column("created_at", DateTime(timezone=True)),
)
